version: 0.2

  #env:
  #variables:
  # key: "value"
  # key: "value"
  #parameter-store:
# key: "value"
# key: "value"
#git-credential-helper: yes

phases:
  install:
    runtime-versions:
      php: 7.3
  build:
    commands:
#      - php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
#      - php composer-setup.php
      - composer install
      - cat vendor/autoload.php

      #post_build:
      #commands:
      # - command
#artifacts:
#  files:
#    - './vendor/**/*'
#    - './composer-cache/**/*'
#    - './root/.composer/**/*'
#  name: artifact-name
cache:
  paths:
    - './vendor/**/*'
    - './composer-cache/**/*'
    - '/root/.composer/**/*'
